//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int Id { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<int> Plazo { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string Estado { get; set; }
    }
}